name: my_local_vendor
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  connectivity_wrapper: ^1.1.0
  country_calling_code_picker: ^2.0.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^4.0.0
  dio: ^4.0.6
  dots_indicator: ^2.1.0
  dropdown_button2: ^1.7.2
  emoji_picker_flutter: ^1.3.1
  firebase_core: ^1.21.1
  firebase_dynamic_links: ^4.3.7
  firebase_messaging: ^11.4.2
  flutter:
    sdk: flutter
  flutter_credit_card: ^3.0.3
  flutter_facebook_auth: ^4.4.1
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.7
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^2.0.0
  flutter_stripe: ^5.0.0
  flutter_svg: ^1.1.1+1
  geocoding: ^2.0.4
  geolocator: ^9.0.1
  get: ^4.6.1
  get_storage: ^2.0.3
  google_sign_in: ^5.4.1
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  mask_text_input_formatter: ^2.4.0
  open_mail_app: ^0.4.5
  permission_handler: ^10.0.0
  persistent_bottom_nav_bar_v2: ^4.2.4
  responsive_sizer: ^3.1.0
  shimmer: ^2.0.0
  sign_in_with_apple: ^4.1.0
  slider_button: ^2.0.0
  syncfusion_flutter_sliders: ^20.2.44
  top_snackbar_flutter: ^1.0.2
  uuid: ^3.0.6
#  uni_links: ^0.5.1
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

flutter_native_splash:
  color: "#141414"
  #  color: "#4520B3"
  #  background_image: "assets/images/splash_logo.png"
  #  image: assets/images/splash_logo.png
  #  branding: assets/images/splash_image.png
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  android: true
  ios: true
  #web: false
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center
  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
  # To enable support for Android 12, set the following parameter to true.  Defaults to false.
  android12: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/locales/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
